### ISSUE TITLE
New Elements not reflected in WFConfig

### ISSUE THREAD

**Issue by eneufeld** [eclipsesource/coffee-editor#272]
When adding a new element to the coffee file, this is not reflected in the wfconfig

**Comment by martin-fleck-at** [comment]
The proposed change ensures that the index is up to date on the language server. However, we do not automatically trigger a re-validation of all *.wfconfig files so if you remove a task that was referenced in one of the *.wfconfig files then you need to manually trigger the validation to see that the reference is no longer valid.

If we want to automatically validate *.wfconfig files on *.coffee updates we probably need to track where which task is used or potentially validate all wfconfig files in a project. Afaik we do not track a list of wfconfig files at the moment so that would need to be done as well or we always iterate over the whole workspace to find all relevant files.
